# Generated by Django 5.1.3 on 2026-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='收货电话'),
        ),
    ]
