# Generated by Django 5.1.3 on 2026-08-08 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('wechat_jsapi', '微信小程序支付'), ('mock', '模拟支付')], default='mock', max_length=16, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('initiated', '已发起'), ('paid', '已支付'), ('refunded', '已退款'), ('failed', '失败')], default='initiated', max_length=16, verbose_name='状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=64, verbose_name='微信支付交易号')),
                ('prepay_id', models.CharField(blank=True, default='', max_length=64, verbose_name='预支付 ID')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='原始响应/回调数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='orders.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付流水',
                'verbose_name_plural': '支付流水',
                'db_table': 'payment_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
