# Generated by Django 5.1.3 on 2026-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('openid', models.CharField(max_length=64, unique=True, verbose_name='微信 openid')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, default='', max_length=512, verbose_name='头像')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
